/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Mateus
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelLocalicao = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        CboxEstado = new javax.swing.JComboBox<>();
        CboxCidade = new javax.swing.JComboBox<>();
        LblEstado = new javax.swing.JLabel();
        LblCidade = new javax.swing.JLabel();
        LblPrevisaoHora = new javax.swing.JLabel();
        LblNextHourTemp = new javax.swing.JLabel();
        LblNext2HourTemp = new javax.swing.JLabel();
        LblNext3HourTemp = new javax.swing.JLabel();
        LblNext4HourTemp = new javax.swing.JLabel();
        sepPainelLocal = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        painelPrevisaoPorHora = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        painelClima = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        painelPrevisaoPorDia = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        barraDeMenu = new javax.swing.JMenuBar();
        menuArquivo = new javax.swing.JMenu();
        subMenuDashboard = new javax.swing.JMenuItem();
        menuArquivoSeparador = new javax.swing.JPopupMenu.Separator();
        subMenuSair = new javax.swing.JMenuItem();
        menuDados = new javax.swing.JMenu();
        subMenuAtualizar = new javax.swing.JMenuItem();
        subMenuHistorico = new javax.swing.JMenuItem();
        menuConfigur = new javax.swing.JMenu();
        subMenuPreferencias = new javax.swing.JMenuItem();
        menuAjuda = new javax.swing.JMenu();
        subMenuSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 2));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel2.setText("Localização");

        LblEstado.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        LblEstado.setText("Estado:");

        LblCidade.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        LblCidade.setText("Cidade:");

        LblPrevisaoHora.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        LblPrevisaoHora.setText("Previsão por hora");

        LblNextHourTemp.setText("Hora");

        LblNext2HourTemp.setText("Hora");

        LblNext3HourTemp.setText("Hora");

        LblNext4HourTemp.setText("Hora");

        jLabel14.setText("Temp");

        jLabel15.setText("Temp");

        jLabel16.setText("Temp");

        jLabel17.setText("Temp");

        painelPrevisaoPorHora.setPreferredSize(new java.awt.Dimension(245, 68));
        painelPrevisaoPorHora.setLayout(new java.awt.GridLayout(1, 4));

        jLabel19.setText("Clima");
        painelPrevisaoPorHora.add(jLabel19);

        jLabel18.setText("Clima");
        painelPrevisaoPorHora.add(jLabel18);

        jLabel20.setText("Clima");
        painelPrevisaoPorHora.add(jLabel20);

        jLabel21.setText("Clima");
        painelPrevisaoPorHora.add(jLabel21);

        javax.swing.GroupLayout painelLocalicaoLayout = new javax.swing.GroupLayout(painelLocalicao);
        painelLocalicao.setLayout(painelLocalicaoLayout);
        painelLocalicaoLayout.setHorizontalGroup(
            painelLocalicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sepPainelLocal, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(painelLocalicaoLayout.createSequentialGroup()
                .addGroup(painelLocalicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelLocalicaoLayout.createSequentialGroup()
                        .addGroup(painelLocalicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelLocalicaoLayout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addGroup(painelLocalicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LblPrevisaoHora)
                                    .addComponent(jLabel2)))
                            .addGroup(painelLocalicaoLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(painelLocalicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(painelLocalicaoLayout.createSequentialGroup()
                                        .addGroup(painelLocalicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(painelLocalicaoLayout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(32, 32, 32)
                                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(28, 28, 28)
                                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(painelLocalicaoLayout.createSequentialGroup()
                                                .addGap(9, 9, 9)
                                                .addComponent(LblNextHourTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(29, 29, 29)
                                                .addComponent(LblNext2HourTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(30, 30, 30)
                                                .addComponent(LblNext3HourTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(26, 26, 26)
                                        .addGroup(painelLocalicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(LblNext4HourTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(painelPrevisaoPorHora, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(painelLocalicaoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(painelLocalicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelLocalicaoLayout.createSequentialGroup()
                                .addComponent(LblEstado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CboxEstado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(painelLocalicaoLayout.createSequentialGroup()
                                .addComponent(LblCidade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CboxCidade, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        painelLocalicaoLayout.setVerticalGroup(
            painelLocalicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLocalicaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(painelLocalicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CboxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblEstado))
                .addGap(18, 18, 18)
                .addGroup(painelLocalicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CboxCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblCidade))
                .addGap(47, 47, 47)
                .addComponent(sepPainelLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblPrevisaoHora)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelLocalicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblNextHourTemp)
                    .addComponent(LblNext2HourTemp)
                    .addComponent(LblNext3HourTemp)
                    .addComponent(LblNext4HourTemp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelPrevisaoPorHora, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelLocalicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addGap(47, 47, 47))
        );

        getContentPane().add(painelLocalicao);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setText("Clima Atual");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel12.setText("Previsão por dia");

        painelPrevisaoPorDia.setLayout(new java.awt.GridLayout(1, 0));

        jLabel13.setText("Clima");
        painelPrevisaoPorDia.add(jLabel13);

        jLabel7.setText("Clima");
        painelPrevisaoPorDia.add(jLabel7);

        jLabel22.setText("Clima");
        painelPrevisaoPorDia.add(jLabel22);

        jLabel23.setText("Clima");
        painelPrevisaoPorDia.add(jLabel23);

        jLabel24.setText(" Dia");

        jLabel25.setText(" Dia");

        jLabel26.setText(" Dia");

        jLabel27.setText(" Dia");

        jLabel28.setText("Temp");

        jLabel29.setText("Temp");

        jLabel30.setText("Temp");

        jLabel31.setText("Temp");

        javax.swing.GroupLayout painelClimaLayout = new javax.swing.GroupLayout(painelClima);
        painelClima.setLayout(painelClimaLayout);
        painelClimaLayout.setHorizontalGroup(
            painelClimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelClimaLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(painelClimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelClimaLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(59, 59, 59))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelClimaLayout.createSequentialGroup()
                        .addComponent(painelPrevisaoPorDia, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))))
            .addGroup(painelClimaLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
            .addGroup(painelClimaLayout.createSequentialGroup()
                .addGroup(painelClimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelClimaLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelClimaLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel12)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelClimaLayout.setVerticalGroup(
            painelClimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelClimaLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addGroup(painelClimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25)
                    .addComponent(jLabel26)
                    .addComponent(jLabel27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelPrevisaoPorDia, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(painelClimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(jLabel29)
                    .addComponent(jLabel30)
                    .addComponent(jLabel31))
                .addGap(37, 37, 37))
        );

        getContentPane().add(painelClima);

        menuArquivo.setText("Arquivo");

        subMenuDashboard.setText("Dashboard");
        subMenuDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuDashboardActionPerformed(evt);
            }
        });
        menuArquivo.add(subMenuDashboard);
        menuArquivo.add(menuArquivoSeparador);

        subMenuSair.setText("Sair");
        menuArquivo.add(subMenuSair);

        barraDeMenu.add(menuArquivo);

        menuDados.setText("Dados");

        subMenuAtualizar.setText("Atualizar dados");
        menuDados.add(subMenuAtualizar);

        subMenuHistorico.setText("Histórico");
        menuDados.add(subMenuHistorico);

        barraDeMenu.add(menuDados);

        menuConfigur.setText("Configurações");

        subMenuPreferencias.setText("Preferencias");
        menuConfigur.add(subMenuPreferencias);

        barraDeMenu.add(menuConfigur);

        menuAjuda.setText("Ajuda");

        subMenuSobre.setText("Sobre");
        subMenuSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuSobreActionPerformed(evt);
            }
        });
        menuAjuda.add(subMenuSobre);

        barraDeMenu.add(menuAjuda);

        setJMenuBar(barraDeMenu);

        setSize(new java.awt.Dimension(635, 471));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void subMenuDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuDashboardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subMenuDashboardActionPerformed

    private void subMenuSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuSobreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subMenuSobreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CboxCidade;
    private javax.swing.JComboBox<String> CboxEstado;
    private javax.swing.JLabel LblCidade;
    private javax.swing.JLabel LblEstado;
    private javax.swing.JLabel LblNext2HourTemp;
    private javax.swing.JLabel LblNext3HourTemp;
    private javax.swing.JLabel LblNext4HourTemp;
    private javax.swing.JLabel LblNextHourTemp;
    private javax.swing.JLabel LblPrevisaoHora;
    private javax.swing.JMenuBar barraDeMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JMenu menuAjuda;
    private javax.swing.JMenu menuArquivo;
    private javax.swing.JPopupMenu.Separator menuArquivoSeparador;
    private javax.swing.JMenu menuConfigur;
    private javax.swing.JMenu menuDados;
    private javax.swing.JPanel painelClima;
    private javax.swing.JPanel painelLocalicao;
    private javax.swing.JPanel painelPrevisaoPorDia;
    private javax.swing.JPanel painelPrevisaoPorHora;
    private javax.swing.JSeparator sepPainelLocal;
    private javax.swing.JMenuItem subMenuAtualizar;
    private javax.swing.JMenuItem subMenuDashboard;
    private javax.swing.JMenuItem subMenuHistorico;
    private javax.swing.JMenuItem subMenuPreferencias;
    private javax.swing.JMenuItem subMenuSair;
    private javax.swing.JMenuItem subMenuSobre;
    // End of variables declaration//GEN-END:variables
}
